# docker-compose.yml

version: '3.7'

services:
  nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - /etc/letsencrypt/live/sparteek65.online:/etc/letsencrypt/live/sparteek65.online
      ports:
        - "9997:80"
        - "9998:443"

  signiling:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python signiling.py
    volumes:
      - .:/app
      - /etc/letsencrypt/live/sparteek65.online:/etc/letsencrypt/live/sparteek65.online
    ports:
      - 9999:9999

