# docker-compose.yml

version: '3.7'

services:
  nginx:
      image: nginx:latest
      container_name: nginx
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - /etc/letsencrypt/live/sparteek65.online:/etc/letsencrypt/live/sparteek65.online
        - ./certbot/conf:/etc/letsencrypt
        - ./certbot/www:/var/www/certbot
      ports:
        - "9997:80"
        - "9998:443"
      depends_on:
        - certbot

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

  signiling:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python signiling.py
    volumes:
      - .:/app
    ports:
      - 9999:9999

