# docker-compose.yml

version: '3.7'

services:
  signiling:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: python -m http.server --bind 0.0.0.0 7000
    volumes:
      - .:/app
    ports:
      - 7000:7000
